#ifndef DARKLOARD_CONFIG_H
#define DARKLOARD_CONFIG_H

#define DARKLOARD_FONT_NAME "Monaspace Xenon"
#define DARKLOARD_FONT_SIZE 75

#define DARKLOARD_MARGIN_TOP 10
#define DARKLOARD_MARGIN_BOTTOM 10
#define DARKLOARD_MARGIN_LEFT 10
#define DARKLOARD_MARGIN_RIGHT 10

#endif // DARKLOARD_CONFIG_H
